name: Update WakaTime Badge

on:
  schedule:
    - cron: '0 */6 * * *' # Каждые 6 часов
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update WakaTime Gist
        uses: matchai/waka-box@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
